### ISSUE TITLE
Very interesting

### ISSUE THREAD

**Issue by BravoSierra** [volkanceylan/Entegra#2]
I'm also working on a project where I might mix Serenity with Delphi. Do you intend to share the same database schema to ensure a smooth transition or will you need to do some significant refactoring to the DB so it will be a complete fork?

**Comment by volkanceylan** [comment]
I actually ported some screens of it into .NET/Serenity in a desktop application, where it worked on existing database with almost no change. For web, only change might be in user/role management as originally there is no user table in database, we were using Firebird users.

**Comment by BravoSierra** [comment]
Can you expand on the difference beetween desktop vs web with Serenity? Do you mean generating classes and DAL and using them from Winforms or WPF?

**Comment by volkanceylan** [comment]
Serenity as DAL and services layer, and some other classes. Used DevExpress Winforms UI.
